version: '3.8'

services:
  web:
    image: python:3
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app.py
    volumes:
      - .:/app/
    port:
      - 3750:3750
    depeds_on:
      - pgdb

  pgdb:
    image: postgres:14
    enviroment:
      POSTGRES_DB: "pgdb"
      POSTGRES_USER: "developer"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "silaeder@admin.org"
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 3751:80
    depends_on:
      - pgdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin
