
services:
  web:
    image: python:3
    build:
      context: .
      dockerfile: Dockerfile
    command: python3 app.py
    volumes:
      - .:/app/
    ports:
      - 3750:3750
    depends_on:
      - pgdb

  pgdb:
    image: postgres:14
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "silaeder@admin.org"
      PGADMIN_DEFAULT_PASSWORD: "${DB_PASSWORD}"
    ports:
      - 3751:80
    depends_on:
      - pgdb
    volumes:
      - pgadmin_data:/var/lib/pgadmin


volumes:
  postgres_data:
  pgadmin_data:
